use DBMSPractical

-- Solution:
-- SET TRANSACTION ISOLATION LEVEL REPEATABLE READ

SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
	SELECT * FROM StudentMember
	WAITFOR DELAY '00:00:05'
	SELECT * FROM StudentMember
COMMIT TRAN